# example of gradient checking

In [29]:
# gradient checking: compare the analytical gradient with the numerical gradient
# taking the affine layer as an example
from gradient_check import eval_numerical_gradient_array
import numpy as np
from layers import *
N = 5
D = 10
M = 4
x = np.random.normal(size=(N, 2,  5))
w = np.random.normal(size=(D, M))
b = np.random.normal(size=(M, ))
dout = np.random.normal(size=(N, M))

# do a forward pass first
out, cache = affine_forward(x, w, b)
# check grad f/grad w, the [0] below gets the output out of the (output, cache) original output

f=lambda w: affine_forward(x, w, b)[0]
# compute the analytical gradient you wrote, [1] get the dw out of the (dx, dw, db) original output
grad = affine_backward(dout, cache)[1]

# compute the numerical gradient using the provided utility function
ngrad = eval_numerical_gradient_array(f, w, dout)
print(grad)
print(ngrad)
# they should be similar enough within some small error tolerance

[[-1.49560496  1.97506978  0.50155959  3.9484664 ]
 [ 1.3776363  -3.27733824  3.006048    4.80752157]
 [ 0.16320426  0.86774584 -0.91588834 -1.77412661]
 [ 4.35644407  2.123704    0.33402112  6.75746938]
 [ 2.37774809 -1.80021958  1.38330244  0.18782212]
 [-1.35906364  3.12024207 -0.14185344  4.15509574]
 [-0.75955635  1.62853224 -1.48258275 -1.37454233]
 [-4.44379565  1.21346864  0.24814847 -0.33948607]
 [-1.47049807  0.67556003  1.49359384  4.58522823]
 [ 6.03755185 -1.1127723   1.31176743  4.35677601]]
[[-1.49560496  1.97506978  0.50155959  3.9484664 ]
 [ 1.3776363  -3.27733824  3.006048    4.80752157]
 [ 0.16320426  0.86774584 -0.91588834 -1.77412661]
 [ 4.35644407  2.123704    0.33402112  6.75746938]
 [ 2.37774809 -1.80021958  1.38330244  0.18782212]
 [-1.35906364  3.12024207 -0.14185344  4.15509574]
 [-0.75955635  1.62853224 -1.48258275 -1.37454233]
 [-4.44379565  1.21346864  0.24814847 -0.33948607]
 [-1.47049807  0.67556003  1.49359384  4.58522823]
 [ 6.03755185 -1.1127723   1.3

# example of training a network

In [2]:
# TODO: put the path to your 'hw6_mds189', which should contain a 'trainval' and 'test' directory
path = '/Users/alexkern/desktop/cs189/cs189_hw6/resources/trainval'
from data_utils import load_mds189

# load the dataset
debug = False  # OPTIONAL: you can change this to True for debugging *only*. Your reported results must be with debug = False
feat_train, label_train, feat_val, label_val = load_mds189(path,debug)
from solver import Solver
from fc_net import FullyConnectedNet



In [30]:
data = {
      'X_train': feat_train,
      'y_train': label_train,
      'X_val': feat_val,
      'y_val': label_val}

# TODO: fill out the hyperparamets
hyperparams = {'lr_decay': .7,
               'num_epochs': 100,
               'batch_size': 1,
               'learning_rate': 2
              }

# TODO: fill out the number of units in your hidden layers
hidden_dim = [] # this should be a list of units for each hiddent layer

model = FullyConnectedNet(input_dim=75,
                          hidden_dim=hidden_dim)
solver = Solver(model, data,
                update_rule='sgd',
                optim_config={
                  'learning_rate': hyperparams['learning_rate'],
                },
                lr_decay=hyperparams['lr_decay'],
                num_epochs=hyperparams['num_epochs'], 
                batch_size=hyperparams['batch_size'],
                print_every=100)
solver.train()

(Iteration 1 / 360000) loss: 0.000000
(Epoch 0 / 100) train acc: 0.158000; val_acc: 0.140203
(Iteration 101 / 360000) loss: 2339229725.052832
(Iteration 201 / 360000) loss: 6545366538.039886
(Iteration 301 / 360000) loss: 9703268929.630608
(Iteration 401 / 360000) loss: 9047718410.860792
(Iteration 501 / 360000) loss: 26832768242.689125
(Iteration 601 / 360000) loss: -0.000000
(Iteration 701 / 360000) loss: 17960739064.930447
(Iteration 801 / 360000) loss: 13983062012.144629
(Iteration 901 / 360000) loss: 30134088112.575554
(Iteration 1001 / 360000) loss: 28509267292.499569
(Iteration 1101 / 360000) loss: 15090944671.568668
(Iteration 1201 / 360000) loss: 41522009485.690544
(Iteration 1301 / 360000) loss: 34733021017.883102
(Iteration 1401 / 360000) loss: 39074684129.170731
(Iteration 1501 / 360000) loss: 48689280694.109482
(Iteration 1601 / 360000) loss: 48881384369.423866
(Iteration 1701 / 360000) loss: 59777855793.090668
(Iteration 1801 / 360000) loss: 62092987813.874130
(Iteration 

(Iteration 17001 / 360000) loss: -0.000000
(Iteration 17101 / 360000) loss: 17432765.306303
(Iteration 17201 / 360000) loss: -0.000000
(Iteration 17301 / 360000) loss: 9467361.197399
(Iteration 17401 / 360000) loss: 12562927.654758
(Iteration 17501 / 360000) loss: 45811911.728605
(Iteration 17601 / 360000) loss: -0.000000
(Iteration 17701 / 360000) loss: 6982864.539198
(Iteration 17801 / 360000) loss: -0.000000
(Iteration 17901 / 360000) loss: 5720710.584707
(Epoch 5 / 100) train acc: 0.121000; val_acc: 0.125000
(Iteration 18001 / 360000) loss: 13510464.310658
(Iteration 18101 / 360000) loss: 4934059.194415
(Iteration 18201 / 360000) loss: 13982193.283128
(Iteration 18301 / 360000) loss: 16197911.252518
(Iteration 18401 / 360000) loss: 5888370.490310
(Iteration 18501 / 360000) loss: 12575279.701295
(Iteration 18601 / 360000) loss: 6032586.302264
(Iteration 18701 / 360000) loss: 4784990.562576
(Iteration 18801 / 360000) loss: 10599847.949956
(Iteration 18901 / 360000) loss: -0.000000
(I

(Iteration 34501 / 360000) loss: 2716401.606287
(Iteration 34601 / 360000) loss: 1500981.338877
(Iteration 34701 / 360000) loss: 155237.415213
(Iteration 34801 / 360000) loss: 3243608.211443
(Iteration 34901 / 360000) loss: 861873.849686
(Iteration 35001 / 360000) loss: 4282955.626787
(Iteration 35101 / 360000) loss: -0.000000
(Iteration 35201 / 360000) loss: 1607402.295127
(Iteration 35301 / 360000) loss: 2294573.158623
(Iteration 35401 / 360000) loss: 128903.272478
(Iteration 35501 / 360000) loss: 3948926.018095
(Iteration 35601 / 360000) loss: 2209504.610347
(Iteration 35701 / 360000) loss: 731073.154154
(Iteration 35801 / 360000) loss: 394633.731553
(Iteration 35901 / 360000) loss: 1771556.025640
(Epoch 10 / 100) train acc: 0.108000; val_acc: 0.125000
(Iteration 36001 / 360000) loss: 845812.487188
(Iteration 36101 / 360000) loss: 2796920.920060
(Iteration 36201 / 360000) loss: 1169328.383307
(Iteration 36301 / 360000) loss: 70532.816682
(Iteration 36401 / 360000) loss: 1259610.2370

(Iteration 51601 / 360000) loss: 206658.161248
(Iteration 51701 / 360000) loss: 124260.154306
(Iteration 51801 / 360000) loss: 391072.652965
(Iteration 51901 / 360000) loss: 332483.499028
(Iteration 52001 / 360000) loss: 206499.586543
(Iteration 52101 / 360000) loss: 252696.364560
(Iteration 52201 / 360000) loss: 723508.196687
(Iteration 52301 / 360000) loss: 312524.207938
(Iteration 52401 / 360000) loss: 226610.408712
(Iteration 52501 / 360000) loss: -0.000000
(Iteration 52601 / 360000) loss: 324829.753743
(Iteration 52701 / 360000) loss: -0.000000
(Iteration 52801 / 360000) loss: -0.000000
(Iteration 52901 / 360000) loss: 583177.440152
(Iteration 53001 / 360000) loss: 343768.400219
(Iteration 53101 / 360000) loss: -0.000000
(Iteration 53201 / 360000) loss: -0.000000
(Iteration 53301 / 360000) loss: -0.000000
(Iteration 53401 / 360000) loss: 200731.922639
(Iteration 53501 / 360000) loss: 527180.550700
(Iteration 53601 / 360000) loss: 330040.136345
(Iteration 53701 / 360000) loss: 2817

(Iteration 69801 / 360000) loss: -0.000000
(Iteration 69901 / 360000) loss: -0.000000
(Iteration 70001 / 360000) loss: -0.000000
(Iteration 70101 / 360000) loss: 3237.522759
(Iteration 70201 / 360000) loss: -0.000000
(Iteration 70301 / 360000) loss: 66892.741761
(Iteration 70401 / 360000) loss: 43835.075003
(Iteration 70501 / 360000) loss: -0.000000
(Iteration 70601 / 360000) loss: -0.000000
(Iteration 70701 / 360000) loss: -0.000000
(Iteration 70801 / 360000) loss: 5205.406338
(Iteration 70901 / 360000) loss: 93141.875568
(Iteration 71001 / 360000) loss: -0.000000
(Iteration 71101 / 360000) loss: 63023.048825
(Iteration 71201 / 360000) loss: 20094.627122
(Iteration 71301 / 360000) loss: 79940.678496
(Iteration 71401 / 360000) loss: 204436.177948
(Iteration 71501 / 360000) loss: -0.000000
(Iteration 71601 / 360000) loss: -0.000000
(Iteration 71701 / 360000) loss: -0.000000
(Iteration 71801 / 360000) loss: -0.000000
(Iteration 71901 / 360000) loss: 80576.118483
(Epoch 20 / 100) train ac

(Iteration 87801 / 360000) loss: -0.000000
(Iteration 87901 / 360000) loss: -0.000000
(Iteration 88001 / 360000) loss: -0.000000
(Iteration 88101 / 360000) loss: -0.000000
(Iteration 88201 / 360000) loss: 7633.447313
(Iteration 88301 / 360000) loss: 2905.394222
(Iteration 88401 / 360000) loss: -0.000000
(Iteration 88501 / 360000) loss: 1588.926755
(Iteration 88601 / 360000) loss: -0.000000
(Iteration 88701 / 360000) loss: -0.000000
(Iteration 88801 / 360000) loss: 1257.548307
(Iteration 88901 / 360000) loss: 12793.835330
(Iteration 89001 / 360000) loss: -0.000000
(Iteration 89101 / 360000) loss: -0.000000
(Iteration 89201 / 360000) loss: -0.000000
(Iteration 89301 / 360000) loss: -0.000000
(Iteration 89401 / 360000) loss: -0.000000
(Iteration 89501 / 360000) loss: -0.000000
(Iteration 89601 / 360000) loss: -0.000000
(Iteration 89701 / 360000) loss: 10864.297002
(Iteration 89801 / 360000) loss: -0.000000
(Iteration 89901 / 360000) loss: -0.000000
(Epoch 25 / 100) train acc: 0.575000; va

(Iteration 106701 / 360000) loss: 243.794931
(Iteration 106801 / 360000) loss: -0.000000
(Iteration 106901 / 360000) loss: -0.000000
(Iteration 107001 / 360000) loss: -0.000000
(Iteration 107101 / 360000) loss: -0.000000
(Iteration 107201 / 360000) loss: -0.000000
(Iteration 107301 / 360000) loss: -0.000000
(Iteration 107401 / 360000) loss: -0.000000
(Iteration 107501 / 360000) loss: -0.000000
(Iteration 107601 / 360000) loss: -0.000000
(Iteration 107701 / 360000) loss: 3201.681406
(Iteration 107801 / 360000) loss: -0.000000
(Iteration 107901 / 360000) loss: -0.000000
(Epoch 30 / 100) train acc: 0.868000; val_acc: 0.856419
(Iteration 108001 / 360000) loss: -0.000000
(Iteration 108101 / 360000) loss: -0.000000
(Iteration 108201 / 360000) loss: -0.000000
(Iteration 108301 / 360000) loss: -0.000000
(Iteration 108401 / 360000) loss: -0.000000
(Iteration 108501 / 360000) loss: -0.000000
(Iteration 108601 / 360000) loss: -0.000000
(Iteration 108701 / 360000) loss: -0.000000
(Iteration 108801

(Iteration 124701 / 360000) loss: -0.000000
(Iteration 124801 / 360000) loss: -0.000000
(Iteration 124901 / 360000) loss: -0.000000
(Iteration 125001 / 360000) loss: -0.000000
(Iteration 125101 / 360000) loss: -0.000000
(Iteration 125201 / 360000) loss: -0.000000
(Iteration 125301 / 360000) loss: -0.000000
(Iteration 125401 / 360000) loss: -0.000000
(Iteration 125501 / 360000) loss: -0.000000
(Iteration 125601 / 360000) loss: -0.000000
(Iteration 125701 / 360000) loss: -0.000000
(Iteration 125801 / 360000) loss: -0.000000
(Iteration 125901 / 360000) loss: -0.000000
(Epoch 35 / 100) train acc: 0.867000; val_acc: 0.816723
(Iteration 126001 / 360000) loss: -0.000000
(Iteration 126101 / 360000) loss: -0.000000
(Iteration 126201 / 360000) loss: -0.000000
(Iteration 126301 / 360000) loss: -0.000000
(Iteration 126401 / 360000) loss: -0.000000
(Iteration 126501 / 360000) loss: -0.000000
(Iteration 126601 / 360000) loss: -0.000000
(Iteration 126701 / 360000) loss: -0.000000
(Iteration 126801 / 

(Iteration 143001 / 360000) loss: -0.000000
(Iteration 143101 / 360000) loss: -0.000000
(Iteration 143201 / 360000) loss: 2499.405122
(Iteration 143301 / 360000) loss: -0.000000
(Iteration 143401 / 360000) loss: -0.000000
(Iteration 143501 / 360000) loss: -0.000000
(Iteration 143601 / 360000) loss: -0.000000
(Iteration 143701 / 360000) loss: 1748.097571
(Iteration 143801 / 360000) loss: -0.000000
(Iteration 143901 / 360000) loss: -0.000000
(Epoch 40 / 100) train acc: 0.927000; val_acc: 0.870777
(Iteration 144001 / 360000) loss: -0.000000
(Iteration 144101 / 360000) loss: -0.000000
(Iteration 144201 / 360000) loss: -0.000000
(Iteration 144301 / 360000) loss: -0.000000
(Iteration 144401 / 360000) loss: 1157.870380
(Iteration 144501 / 360000) loss: -0.000000
(Iteration 144601 / 360000) loss: -0.000000
(Iteration 144701 / 360000) loss: -0.000000
(Iteration 144801 / 360000) loss: -0.000000
(Iteration 144901 / 360000) loss: -0.000000
(Iteration 145001 / 360000) loss: -0.000000
(Iteration 145

(Iteration 162001 / 360000) loss: 806.106328
(Iteration 162101 / 360000) loss: -0.000000
(Iteration 162201 / 360000) loss: -0.000000
(Iteration 162301 / 360000) loss: -0.000000
(Iteration 162401 / 360000) loss: -0.000000
(Iteration 162501 / 360000) loss: -0.000000
(Iteration 162601 / 360000) loss: -0.000000
(Iteration 162701 / 360000) loss: -0.000000
(Iteration 162801 / 360000) loss: -0.000000
(Iteration 162901 / 360000) loss: -0.000000
(Iteration 163001 / 360000) loss: -0.000000
(Iteration 163101 / 360000) loss: -0.000000
(Iteration 163201 / 360000) loss: -0.000000
(Iteration 163301 / 360000) loss: -0.000000
(Iteration 163401 / 360000) loss: -0.000000
(Iteration 163501 / 360000) loss: -0.000000
(Iteration 163601 / 360000) loss: -0.000000
(Iteration 163701 / 360000) loss: 74.326646
(Iteration 163801 / 360000) loss: -0.000000
(Iteration 163901 / 360000) loss: -0.000000
(Iteration 164001 / 360000) loss: -0.000000
(Iteration 164101 / 360000) loss: -0.000000
(Iteration 164201 / 360000) los

(Iteration 180901 / 360000) loss: -0.000000
(Iteration 181001 / 360000) loss: -0.000000
(Iteration 181101 / 360000) loss: -0.000000
(Iteration 181201 / 360000) loss: -0.000000
(Iteration 181301 / 360000) loss: -0.000000
(Iteration 181401 / 360000) loss: -0.000000
(Iteration 181501 / 360000) loss: -0.000000
(Iteration 181601 / 360000) loss: -0.000000
(Iteration 181701 / 360000) loss: -0.000000
(Iteration 181801 / 360000) loss: -0.000000
(Iteration 181901 / 360000) loss: -0.000000
(Iteration 182001 / 360000) loss: -0.000000
(Iteration 182101 / 360000) loss: -0.000000
(Iteration 182201 / 360000) loss: -0.000000
(Iteration 182301 / 360000) loss: -0.000000
(Iteration 182401 / 360000) loss: -0.000000
(Iteration 182501 / 360000) loss: -0.000000
(Iteration 182601 / 360000) loss: -0.000000
(Iteration 182701 / 360000) loss: -0.000000
(Iteration 182801 / 360000) loss: -0.000000
(Iteration 182901 / 360000) loss: -0.000000
(Iteration 183001 / 360000) loss: -0.000000
(Iteration 183101 / 360000) loss

(Iteration 199301 / 360000) loss: 37.075438
(Iteration 199401 / 360000) loss: -0.000000
(Iteration 199501 / 360000) loss: -0.000000
(Iteration 199601 / 360000) loss: -0.000000
(Iteration 199701 / 360000) loss: -0.000000
(Iteration 199801 / 360000) loss: -0.000000
(Iteration 199901 / 360000) loss: 1658.237448
(Iteration 200001 / 360000) loss: -0.000000
(Iteration 200101 / 360000) loss: -0.000000
(Iteration 200201 / 360000) loss: -0.000000
(Iteration 200301 / 360000) loss: -0.000000
(Iteration 200401 / 360000) loss: 439.116395
(Iteration 200501 / 360000) loss: -0.000000
(Iteration 200601 / 360000) loss: 15.267413
(Iteration 200701 / 360000) loss: -0.000000
(Iteration 200801 / 360000) loss: -0.000000
(Iteration 200901 / 360000) loss: -0.000000
(Iteration 201001 / 360000) loss: -0.000000
(Iteration 201101 / 360000) loss: -0.000000
(Iteration 201201 / 360000) loss: 731.083527
(Iteration 201301 / 360000) loss: -0.000000
(Iteration 201401 / 360000) loss: 0.439313
(Iteration 201501 / 360000) l

(Iteration 217501 / 360000) loss: -0.000000
(Iteration 217601 / 360000) loss: -0.000000
(Iteration 217701 / 360000) loss: -0.000000
(Iteration 217801 / 360000) loss: -0.000000
(Iteration 217901 / 360000) loss: -0.000000
(Iteration 218001 / 360000) loss: 1804.717676
(Iteration 218101 / 360000) loss: -0.000000
(Iteration 218201 / 360000) loss: -0.000000
(Iteration 218301 / 360000) loss: 175.866170
(Iteration 218401 / 360000) loss: -0.000000
(Iteration 218501 / 360000) loss: -0.000000
(Iteration 218601 / 360000) loss: -0.000000
(Iteration 218701 / 360000) loss: -0.000000
(Iteration 218801 / 360000) loss: -0.000000
(Iteration 218901 / 360000) loss: -0.000000
(Iteration 219001 / 360000) loss: -0.000000
(Iteration 219101 / 360000) loss: -0.000000
(Iteration 219201 / 360000) loss: -0.000000
(Iteration 219301 / 360000) loss: -0.000000
(Iteration 219401 / 360000) loss: 791.859826
(Iteration 219501 / 360000) loss: -0.000000
(Epoch 61 / 100) train acc: 0.927000; val_acc: 0.885135
(Iteration 21960

(Iteration 235701 / 360000) loss: -0.000000
(Iteration 235801 / 360000) loss: -0.000000
(Iteration 235901 / 360000) loss: -0.000000
(Iteration 236001 / 360000) loss: 0.000000
(Iteration 236101 / 360000) loss: -0.000000
(Iteration 236201 / 360000) loss: -0.000000
(Iteration 236301 / 360000) loss: -0.000000
(Iteration 236401 / 360000) loss: -0.000000
(Iteration 236501 / 360000) loss: -0.000000
(Iteration 236601 / 360000) loss: -0.000000
(Iteration 236701 / 360000) loss: -0.000000
(Iteration 236801 / 360000) loss: -0.000000
(Iteration 236901 / 360000) loss: -0.000000
(Iteration 237001 / 360000) loss: -0.000000
(Iteration 237101 / 360000) loss: -0.000000
(Iteration 237201 / 360000) loss: -0.000000
(Iteration 237301 / 360000) loss: -0.000000
(Iteration 237401 / 360000) loss: -0.000000
(Iteration 237501 / 360000) loss: -0.000000
(Epoch 66 / 100) train acc: 0.922000; val_acc: 0.885135
(Iteration 237601 / 360000) loss: -0.000000
(Iteration 237701 / 360000) loss: -0.000000
(Iteration 237801 / 3

(Iteration 254001 / 360000) loss: 357.010339
(Iteration 254101 / 360000) loss: -0.000000
(Iteration 254201 / 360000) loss: -0.000000
(Iteration 254301 / 360000) loss: -0.000000
(Iteration 254401 / 360000) loss: 1.562382
(Iteration 254501 / 360000) loss: 262.091445
(Iteration 254601 / 360000) loss: -0.000000
(Iteration 254701 / 360000) loss: -0.000000
(Iteration 254801 / 360000) loss: -0.000000
(Iteration 254901 / 360000) loss: -0.000000
(Iteration 255001 / 360000) loss: -0.000000
(Iteration 255101 / 360000) loss: -0.000000
(Iteration 255201 / 360000) loss: -0.000000
(Iteration 255301 / 360000) loss: -0.000000
(Iteration 255401 / 360000) loss: -0.000000
(Iteration 255501 / 360000) loss: -0.000000
(Epoch 71 / 100) train acc: 0.934000; val_acc: 0.885135
(Iteration 255601 / 360000) loss: -0.000000
(Iteration 255701 / 360000) loss: -0.000000
(Iteration 255801 / 360000) loss: -0.000000
(Iteration 255901 / 360000) loss: -0.000000
(Iteration 256001 / 360000) loss: -0.000000
(Iteration 256101 /

(Iteration 273301 / 360000) loss: -0.000000
(Iteration 273401 / 360000) loss: -0.000000
(Iteration 273501 / 360000) loss: -0.000000
(Epoch 76 / 100) train acc: 0.947000; val_acc: 0.885135
(Iteration 273601 / 360000) loss: -0.000000
(Iteration 273701 / 360000) loss: -0.000000
(Iteration 273801 / 360000) loss: -0.000000
(Iteration 273901 / 360000) loss: -0.000000
(Iteration 274001 / 360000) loss: -0.000000
(Iteration 274101 / 360000) loss: -0.000000
(Iteration 274201 / 360000) loss: -0.000000
(Iteration 274301 / 360000) loss: -0.000000
(Iteration 274401 / 360000) loss: -0.000000
(Iteration 274501 / 360000) loss: -0.000000
(Iteration 274601 / 360000) loss: -0.000000
(Iteration 274701 / 360000) loss: -0.000000
(Iteration 274801 / 360000) loss: -0.000000
(Iteration 274901 / 360000) loss: -0.000000
(Iteration 275001 / 360000) loss: -0.000000
(Iteration 275101 / 360000) loss: -0.000000
(Iteration 275201 / 360000) loss: 2192.378911
(Iteration 275301 / 360000) loss: -0.000000
(Iteration 275401 

(Iteration 292001 / 360000) loss: -0.000000
(Iteration 292101 / 360000) loss: -0.000000
(Iteration 292201 / 360000) loss: -0.000000
(Iteration 292301 / 360000) loss: -0.000000
(Iteration 292401 / 360000) loss: -0.000000
(Iteration 292501 / 360000) loss: -0.000000
(Iteration 292601 / 360000) loss: -0.000000
(Iteration 292701 / 360000) loss: -0.000000
(Iteration 292801 / 360000) loss: -0.000000
(Iteration 292901 / 360000) loss: -0.000000
(Iteration 293001 / 360000) loss: -0.000000
(Iteration 293101 / 360000) loss: -0.000000
(Iteration 293201 / 360000) loss: -0.000000
(Iteration 293301 / 360000) loss: -0.000000
(Iteration 293401 / 360000) loss: -0.000000
(Iteration 293501 / 360000) loss: -0.000000
(Iteration 293601 / 360000) loss: -0.000000
(Iteration 293701 / 360000) loss: 81.490455
(Iteration 293801 / 360000) loss: -0.000000
(Iteration 293901 / 360000) loss: 343.351670
(Iteration 294001 / 360000) loss: -0.000000
(Iteration 294101 / 360000) loss: -0.000000
(Iteration 294201 / 360000) los

(Iteration 311001 / 360000) loss: -0.000000
(Iteration 311101 / 360000) loss: -0.000000
(Iteration 311201 / 360000) loss: -0.000000
(Iteration 311301 / 360000) loss: -0.000000
(Iteration 311401 / 360000) loss: -0.000000
(Iteration 311501 / 360000) loss: -0.000000
(Iteration 311601 / 360000) loss: -0.000000
(Iteration 311701 / 360000) loss: -0.000000
(Iteration 311801 / 360000) loss: -0.000000
(Iteration 311901 / 360000) loss: -0.000000
(Iteration 312001 / 360000) loss: -0.000000
(Iteration 312101 / 360000) loss: -0.000000
(Iteration 312201 / 360000) loss: -0.000000
(Iteration 312301 / 360000) loss: -0.000000
(Iteration 312401 / 360000) loss: -0.000000
(Iteration 312501 / 360000) loss: -0.000000
(Iteration 312601 / 360000) loss: -0.000000
(Iteration 312701 / 360000) loss: -0.000000
(Iteration 312801 / 360000) loss: -0.000000
(Iteration 312901 / 360000) loss: -0.000000
(Iteration 313001 / 360000) loss: -0.000000
(Iteration 313101 / 360000) loss: -0.000000
(Epoch 87 / 100) train acc: 0.93

(Iteration 330101 / 360000) loss: -0.000000
(Iteration 330201 / 360000) loss: 208.660902
(Iteration 330301 / 360000) loss: -0.000000
(Iteration 330401 / 360000) loss: -0.000000
(Iteration 330501 / 360000) loss: -0.000000
(Iteration 330601 / 360000) loss: -0.000000
(Iteration 330701 / 360000) loss: 1.861295
(Iteration 330801 / 360000) loss: 896.264093
(Iteration 330901 / 360000) loss: -0.000000
(Iteration 331001 / 360000) loss: -0.000000
(Iteration 331101 / 360000) loss: -0.000000
(Epoch 92 / 100) train acc: 0.938000; val_acc: 0.885135
(Iteration 331201 / 360000) loss: -0.000000
(Iteration 331301 / 360000) loss: -0.000000
(Iteration 331401 / 360000) loss: -0.000000
(Iteration 331501 / 360000) loss: -0.000000
(Iteration 331601 / 360000) loss: -0.000000
(Iteration 331701 / 360000) loss: -0.000000
(Iteration 331801 / 360000) loss: 69.301491
(Iteration 331901 / 360000) loss: -0.000000
(Iteration 332001 / 360000) loss: -0.000000
(Iteration 332101 / 360000) loss: -0.000000
(Iteration 332201 /

(Iteration 348801 / 360000) loss: -0.000000
(Iteration 348901 / 360000) loss: -0.000000
(Iteration 349001 / 360000) loss: -0.000000
(Iteration 349101 / 360000) loss: -0.000000
(Epoch 97 / 100) train acc: 0.925000; val_acc: 0.885135
(Iteration 349201 / 360000) loss: -0.000000
(Iteration 349301 / 360000) loss: 122.937831
(Iteration 349401 / 360000) loss: -0.000000
(Iteration 349501 / 360000) loss: -0.000000
(Iteration 349601 / 360000) loss: 16.409388
(Iteration 349701 / 360000) loss: -0.000000
(Iteration 349801 / 360000) loss: -0.000000
(Iteration 349901 / 360000) loss: -0.000000
(Iteration 350001 / 360000) loss: -0.000000
(Iteration 350101 / 360000) loss: -0.000000
(Iteration 350201 / 360000) loss: 52.656957
(Iteration 350301 / 360000) loss: -0.000000
(Iteration 350401 / 360000) loss: 4372.105142
(Iteration 350501 / 360000) loss: -0.000000
(Iteration 350601 / 360000) loss: -0.000000
(Iteration 350701 / 360000) loss: 178.137489
(Iteration 350801 / 360000) loss: -0.000000
(Iteration 35090